using System.Text;
using System.Text.Json;
using ZeroBrowser.Core.Models;

namespace ZeroBrowser.Storage.Cookies;

/// <summary>
/// Per-profile cookie persistence. Stores imported cookies as JSON in
/// <c>{profile.StoragePath}/imported-cookies.json</c>. The launcher reads this
/// file on launch and applies the cookies before navigation.
/// </summary>
public static class CookieStore
{
    public const string FileName = "imported-cookies.json";

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
    };

    public static string PathFor(string profileStorageDir) => Path.Combine(profileStorageDir, FileName);

    public static IReadOnlyList<CookieRecord> Load(string profileStorageDir)
    {
        var path = PathFor(profileStorageDir);
        if (!File.Exists(path)) return Array.Empty<CookieRecord>();
        try
        {
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize<List<CookieRecord>>(json) ?? new();
        }
        catch
        {
            return Array.Empty<CookieRecord>();
        }
    }

    public static void Save(string profileStorageDir, IEnumerable<CookieRecord> cookies)
    {
        Directory.CreateDirectory(profileStorageDir);
        var path = PathFor(profileStorageDir);
        File.WriteAllText(path, JsonSerializer.Serialize(cookies, JsonOpts));
        // Restrict file permissions so other OS users can't read session cookies.
        // On Windows this is best-effort; on Linux/macOS it sets mode 0600.
        try
        {
            var info = new FileInfo(path);
            if (!OperatingSystem.IsWindows())
            {
                File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
            }
        }
        catch { /* best-effort */ }
    }

    public static void Clear(string profileStorageDir)
    {
        var path = PathFor(profileStorageDir);
        if (File.Exists(path)) File.Delete(path);
    }

    // ---- Export ----

    /// <summary>Export cookies as JSON array (Playwright/Puppeteer compatible).</summary>
    public static string ExportJson(string profileStorageDir)
    {
        var cookies = Load(profileStorageDir);
        return JsonSerializer.Serialize(cookies, JsonOpts);
    }

    /// <summary>
    /// Export cookies as Netscape HTTP Cookie File format (curl/wget compatible).
    /// Lines: domain flag path secure expires name value (tab-separated).
    /// </summary>
    public static string ExportNetscape(string profileStorageDir)
    {
        var cookies = Load(profileStorageDir);
        var sb = new StringBuilder();
        sb.AppendLine("# Netscape HTTP Cookie File");
        sb.AppendLine("# Generated by ZeroBrowser");
        sb.AppendLine("#");
        foreach (var c in cookies)
        {
            var domain    = c.Domain.StartsWith('.') ? c.Domain : "." + c.Domain;
            var flag      = "TRUE";
            var path      = string.IsNullOrEmpty(c.Path) ? "/" : c.Path;
            var secure    = c.Secure == true ? "TRUE" : "FALSE";
            var expires   = c.ExpiresUnix ?? 0;
            if (expires < 0) expires = 0;
            sb.AppendLine($"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c.Name}\t{c.Value}");
        }
        return sb.ToString();
    }

    /// <summary>Save exported cookies to a file. Returns the file path.</summary>
    public static string ExportToFile(string profileStorageDir, string format, string? outputPath = null)
    {
        var content = format.ToLowerInvariant() switch
        {
            "netscape" => ExportNetscape(profileStorageDir),
            _          => ExportJson(profileStorageDir)
        };
        var ext = format.ToLowerInvariant() == "netscape" ? ".txt" : ".json";
        var path = outputPath ?? Path.Combine(profileStorageDir, $"exported-cookies{ext}");
        File.WriteAllText(path, content);
        return path;
    }
}
